<?php

/**
 * JoboardAffiliateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JoboardAffiliateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JoboardAffiliateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JoboardAffiliate');
    }
}