<?php

/**
 * JoboardJobTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JoboardJobTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JoboardJobTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JoboardJob');
    }
}