<?php

/**
 * JoboardCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JoboardCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JoboardCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('JoboardCategory');
    }
}