<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/12/18 10:53:48

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=joboard',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
